services:
  db:
    image: postgres:14.5
    container_name: postgres
    volumes:
      - pgdata:/var/var/lib/postgresql/data
    env_file:
      - .env
  main_app:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: app
    depends_on:
      - db
    env_file:
      - .env
